/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package praktikum170625;

/**
 *
 * @author rakad
 */
public class MenuMinuman extends javax.swing.JFrame {

    private MenuUtama utama;
    
    public MenuMinuman(MenuUtama utama){
        this.utama = utama;
        initComponents();
    }
    public MenuMinuman() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPop = new javax.swing.JTextField();
        txtChoco = new javax.swing.JTextField();
        btnTotal = new javax.swing.JButton();
        cbJoss = new javax.swing.JComboBox<>();
        btnKembali = new javax.swing.JButton();
        cbEs = new javax.swing.JComboBox<>();
        txtTotal = new javax.swing.JTextField();
        cbPop = new javax.swing.JComboBox<>();
        chkJoss = new javax.swing.JCheckBox();
        cbChoco = new javax.swing.JComboBox<>();
        chkEs = new javax.swing.JCheckBox();
        chkPop = new javax.swing.JCheckBox();
        txtTotJoss = new javax.swing.JTextField();
        chkChoco = new javax.swing.JCheckBox();
        txtTotEs = new javax.swing.JTextField();
        txtJoss = new javax.swing.JTextField();
        txtTotChoco = new javax.swing.JTextField();
        txtEs = new javax.swing.JTextField();
        txtTotPop = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 600));

        txtPop.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPop.setText("0");
        txtPop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPopActionPerformed(evt);
            }
        });

        txtChoco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtChoco.setText("0");

        btnTotal.setBackground(new java.awt.Color(204, 255, 204));
        btnTotal.setText("Total");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        cbJoss.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbJoss.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        cbJoss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJossActionPerformed(evt);
            }
        });

        btnKembali.setText("Kembali ke Menu Utama");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        cbEs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbEs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        cbEs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEsActionPerformed(evt);
            }
        });

        txtTotal.setText("0");

        cbPop.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbPop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbPop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPopActionPerformed(evt);
            }
        });

        chkJoss.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkJoss.setText("ExtraJoss Susu");
        chkJoss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkJossActionPerformed(evt);
            }
        });

        cbChoco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbChoco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        cbChoco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbChocoActionPerformed(evt);
            }
        });

        chkEs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkEs.setText("Es Teh");
        chkEs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEsActionPerformed(evt);
            }
        });

        chkPop.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkPop.setText("Pop Ice Taro");
        chkPop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPopActionPerformed(evt);
            }
        });

        txtTotJoss.setText("0");
        txtTotJoss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotJossActionPerformed(evt);
            }
        });

        chkChoco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkChoco.setText("Chocolatos");
        chkChoco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkChocoActionPerformed(evt);
            }
        });

        txtTotEs.setText("0");

        txtJoss.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtJoss.setText("0");

        txtTotChoco.setText("0");

        txtEs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEs.setText("0");

        txtTotPop.setText("0");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("MENU MINUMAN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkEs)
                    .addComponent(chkJoss)
                    .addComponent(chkPop)
                    .addComponent(chkChoco))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEs, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJoss, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPop, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChoco, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbJoss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbEs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbPop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbChoco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotChoco, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotEs, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotJoss, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotPop, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkJoss)
                    .addComponent(txtJoss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbJoss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotJoss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkEs)
                    .addComponent(txtEs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotEs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkPop)
                    .addComponent(txtPop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotPop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkChoco)
                    .addComponent(txtChoco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbChoco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotChoco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(814, 508));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPopActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        double joss = Double.parseDouble(txtTotJoss.getText());
        double esteh = Double.parseDouble(txtTotEs.getText());
        double popice = Double.parseDouble(txtTotPop.getText());
        double choco = Double.parseDouble(txtTotChoco.getText());
        double total = joss+esteh+popice+choco;
        txtTotal.setText(Double.toString(total));
        //atau
        //txtTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_btnTotalActionPerformed

    private void cbJossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJossActionPerformed
        int jml = (int)cbJoss.getSelectedIndex();
        double harga = Double.parseDouble(txtJoss.getText());
        double total = jml*harga;
        txtTotJoss.setText(Double.toString(total));
    }//GEN-LAST:event_cbJossActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        String total = txtTotal.getText();
        utama.setTotalMinuman(total);
        this.dispose(); // menutup jendela form menu makanan
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void cbEsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEsActionPerformed
        int jml = (int)cbEs.getSelectedIndex();
        double harga = Double.parseDouble(txtEs.getText());
        double total = jml*harga;
        txtTotEs.setText(Double.toString(total));
    }//GEN-LAST:event_cbEsActionPerformed

    private void cbPopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPopActionPerformed
        int jml = (int)cbPop.getSelectedIndex();
        double harga = Double.parseDouble(txtPop.getText());
        double total = jml*harga;
        txtTotPop.setText(Double.toString(total));
    }//GEN-LAST:event_cbPopActionPerformed

    private void chkJossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkJossActionPerformed
        txtJoss.setText("17000");
    }//GEN-LAST:event_chkJossActionPerformed

    private void cbChocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbChocoActionPerformed
        int jml = (int)cbChoco.getSelectedIndex();
        double harga = Double.parseDouble(txtChoco.getText());
        double total = jml*harga;
        txtTotChoco.setText(Double.toString(total));
    }//GEN-LAST:event_cbChocoActionPerformed

    private void chkEsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEsActionPerformed
        txtEs.setText("10000");
    }//GEN-LAST:event_chkEsActionPerformed

    private void chkPopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPopActionPerformed
        txtPop.setText("13000");
    }//GEN-LAST:event_chkPopActionPerformed

    private void txtTotJossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotJossActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotJossActionPerformed

    private void chkChocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkChocoActionPerformed
        txtChoco.setText("12000");
    }//GEN-LAST:event_chkChocoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuMinuman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTotal;
    private javax.swing.JComboBox<String> cbChoco;
    private javax.swing.JComboBox<String> cbEs;
    private javax.swing.JComboBox<String> cbJoss;
    private javax.swing.JComboBox<String> cbPop;
    private javax.swing.JCheckBox chkChoco;
    private javax.swing.JCheckBox chkEs;
    private javax.swing.JCheckBox chkJoss;
    private javax.swing.JCheckBox chkPop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtChoco;
    private javax.swing.JTextField txtEs;
    private javax.swing.JTextField txtJoss;
    private javax.swing.JTextField txtPop;
    private javax.swing.JTextField txtTotChoco;
    private javax.swing.JTextField txtTotEs;
    private javax.swing.JTextField txtTotJoss;
    private javax.swing.JTextField txtTotPop;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
