/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package praktikum030625;

/**
 *
 * @author rakad
 */
public class PolaPerulanganBersarang extends javax.swing.JFrame {

    /**
     * Creates new form PolaPerulanganBersarang
     */
    public PolaPerulanganBersarang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtBaris = new javax.swing.JTextField();
        txtKolom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbPola = new javax.swing.JComboBox<>();
        btnProses = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaPola = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("POLA PERULANGAN BERSARANG");

        jLabel2.setText("Masukkan Jumlah Baris");

        jLabel3.setText("Masukkan Jumlah Kolom");

        txtBaris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBarisActionPerformed(evt);
            }
        });

        txtKolom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKolomActionPerformed(evt);
            }
        });

        jLabel4.setText("Masukkan Jumlah Pola");

        cbPola.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pola", "Kotak", "Kotak Garis Melintang", "Segitiga Siku-Siku", "Segitiga", "Segitiga Terbalik", "Jajar Genjang", "Huruf R" }));
        cbPola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPolaActionPerformed(evt);
            }
        });

        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        areaPola.setColumns(20);
        areaPola.setRows(5);
        jScrollPane1.setViewportView(areaPola);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addComponent(btnProses)
                        .addGap(37, 37, 37))))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(152, 152, 152)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtKolom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(txtBaris, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbPola, javax.swing.GroupLayout.Alignment.TRAILING, 0, 1, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBaris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKolom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbPola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProses))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(614, 508));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBarisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBarisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBarisActionPerformed

    private void txtKolomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKolomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKolomActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        int a = Integer.parseInt(txtBaris.getText());
        int b = Integer.parseInt(txtKolom.getText());
        int pola = (int) cbPola.getSelectedIndex();
        StringBuilder output = new StringBuilder();
        int i, j;

        switch (pola) {
            case 1: {
                for (i = 0; i < a; i++) {
                    for (j = 0; j < b; j++) {
                        if (i == 0 || i == a - 1 || j == 0 || j == a - 1) {
                            output.append(" * ");
                        } else {
                            output.append("   ");
                        }
                    }
                    output.append("\n");
                }
            }
            break;
            case 2: {
                for (i = 0; i < a; i++) {
                    for (j = 0; j < b; j++) {
                        if (i == 0 || i == a - 1 || j == 0 || j == a - 1 || i == j || j == i) {
                            output.append(" * ");
                        } else {
                            output.append("   ");
                        }
                    }
                    output.append("\n");
                }
            }
            break;
            case 3: {
                for (i = 0; i < a; i++) {
                    for (j = b - 1; j >= i; j--) {
                        output.append("   ");
                    }
                    for (j = 0; j <= i; j++) {
                        output.append(" * ");
                    }
                    output.append("\n\n");
                }
            }
            break;
            case 4: {
                for (i = 0; i < a; i++) {
                    for (j = b - 1; j >= i; j--) {
                        output.append("   ");
                    }
                    for (j = 0; j <= i; j++) {
                        output.append(" * ");
                    }
                    for (j = 1; j <= i; j++) {
                        output.append(" * ");
                    }
                    output.append("\n\n");
                }
            }
            break;
            case 5: {
                for (i = 0; i < a; i++) {
                    for (j = 0; j <= i; j++) {
                        output.append(" * ");
                    }
                    for (j = b - 1; j >= i; j--) {
                        output.append("   ");
                    }
                    for (j = b - 1; j >= i; j--) {
                        output.append("   ");
                    }
                    for (j = 0; j <= i; j++) {
                        output.append(" * ");
                    }
                    output.append("\n\n");
                }
            }
            break;
            case 6: {
                for (i = 0; i < a; i++) {
                    for (j = 0; j <= i; j++) {
                        output.append("  ");
                    }
                    for (j = 0; j < b; j++) {
                        output.append("  *  ");
                    }
                    output.append("\n\n");
                }
            }
            break;
            case 7: {
                for (i = 0; i < b; i++) {
                    for (j = 0; j < a; j++) {
                        if (j == 0
                                || (i == 0 && j < a - 1)
                                || (i == b / 2 && j < a - 1)
                                || (j == a - 1 && i > 0 && i < b / 2)
                                || (i > b / 2 && j == i - (b / 2) + 1)) {
                            output.append("*");
                        } else {
                            output.append(" ");
                        }
                    }
                    output.append("\n");
                }
            }
            break;
        }
        areaPola.setText(output.toString());
    }//GEN-LAST:event_btnProsesActionPerformed

    private void cbPolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PolaPerulanganBersarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PolaPerulanganBersarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PolaPerulanganBersarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PolaPerulanganBersarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PolaPerulanganBersarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaPola;
    private javax.swing.JButton btnProses;
    private javax.swing.JComboBox<String> cbPola;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBaris;
    private javax.swing.JTextField txtKolom;
    // End of variables declaration//GEN-END:variables
}
